PACKAGE_NAME="eg"
PACKAGE_VERSION="2.0"

BUILT_MODULE_NAME[0]="eg"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNELDIR=${kernel_source_dir} KVER=${kernelver}"
CLEAN="make KERNELDIR=${kernel_source_dir} KVER=${kernelver} clean"

AUTOINSTALL="yes"
